import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
          <Link
              href="/info"> 

          <svg width="100" height="100" viewBox="0 0 75 75" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M23.1538 21.3077H25V37.9231H26.8462M49 25C49 31.3652 46.4714 37.4697 41.9706 41.9706C37.4697 46.4714 31.3652 49 25 49C18.6348 49 12.5303 46.4714 8.02944 41.9706C3.52856 37.4697 1 31.3652 1 25C1 18.6348 3.52856 12.5303 8.02944 8.02944C12.5303 3.52856 18.6348 1 25 1C31.3652 1 37.4697 3.52856 41.9706 8.02944C46.4714 12.5303 49 18.6348 49 25Z" stroke="black" strokeWidth="2" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M27 15C27 15.5304 26.7893 16.0391 26.4142 16.4142C26.0391 16.7893 25.5304 17 25 17C24.4696 17 23.9609 16.7893 23.5858 16.4142C23.2107 16.0391 23 15.5304 23 15C23 14.4696 23.2107 13.9609 23.5858 13.5858C23.9609 13.2107 24.4696 13 25 13C25.5304 13 26.0391 13.2107 26.4142 13.5858C26.7893 13.9609 27 14.4696 27 15Z" fill="black" stroke="black"/>
          </svg>

          </Link>
          </div>
          <div>
            <a
              href="https://climateincolour.com/"
              target="_blank"
              rel="noopener noreferrer"
            >
              By
              <svg  xmlns="http://www.w3.org/2000/svg" width="56" height="56" viewBox="0 0 56 56"><g data-name="Group 111" transform="translate(-10.502 -593.756)"><g data-name="Path 54"><path data-name="Path 55" d="M38.5,594.756a26.987,26.987,0,1,0,22.547,41.931,25.933,25.933,0,0,0,3.531-7.908,27.453,27.453,0,0,0,.922-7.023,26.976,26.976,0,0,0-27-27" fill="#EF9D16" stroke="#000000" stroke-miterlimit="10" stroke-width="2"></path></g><g style={{isolation: 'isolate'}}><g data-name="Group 110" style={{isolation: 'isolate'}}><path data-name="Path 56" d="M33.061,603.669a19.987,19.987,0,0,1,7.521-1.449c5.451,0,10.9,2.345,11.247,8.625a3.594,3.594,0,0,1-.553,2.345c-.9,1.173-2.138,1.243-3.38,1.864-2.07,1.035-2.691,4.209-5.382,4.209a2.523,2.523,0,0,1-2.347-2.346c0-2.14.622-3.381.966-5.451a10.214,10.214,0,0,0,.138-1.519c0-2.828-1.241-5.726-3.519-5.726a4.737,4.737,0,0,0-2.69,1.1c-3.244,2.484-3.588,6.486-3.588,10.419,0,6.555,2.966,18.285,11.454,18.285,2.07,0,3.519-.9,5.175-2.07,5.588-3.934,6.969-11.385,6.969-17.8a.919.919,0,0,1,.966.69,14.819,14.819,0,0,1,.138,3.036c0,14.144-9.936,22.011-19.942,22.149H35.89c-10.282,0-16.009-6.831-16.009-16.9C19.881,614.433,24.436,607.326,33.061,603.669Z" fill="#000000"></path></g></g></g></svg>

            </a>
          </div>
        </div>

        <div className={styles.center}>
            <button className={styles.buttonStart}> <Link href='/cluster'>Get Started </Link> </button>
        </div>

        <div className={styles.footer}>
          <div className={styles.soundIcon}>
          <svg width="42" height="30" viewBox="0 0 42 30" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M1 20V12C1 11.4696 1.21071 10.9608 1.58579 10.5858C1.96086 10.2107 2.46957 9.99999 3 9.99999H8.394C8.78906 10.0001 9.17531 9.88316 9.504 9.66399L17.89 4.07199C18.1915 3.87084 18.542 3.7554 18.904 3.73799C19.266 3.72059 19.6259 3.80188 19.9453 3.97318C20.2647 4.14448 20.5315 4.39935 20.7173 4.71054C20.9031 5.02174 21.0008 5.37756 21 5.73999V26.26C21.0001 26.6221 20.9018 26.9774 20.7157 27.288C20.5297 27.5986 20.2628 27.8529 19.9435 28.0237C19.6243 28.1946 19.2646 28.2755 18.903 28.2579C18.5413 28.2404 18.1912 28.1249 17.89 27.924L9.504 22.334C9.17508 22.1155 8.78886 21.9993 8.394 22H3C2.46957 22 1.96086 21.7893 1.58579 21.4142C1.21071 21.0391 1 20.5304 1 20Z" stroke="black" stroke-width="1.5"/>
          <path d="M30 7C30 7 33 10 33 15C33 20 30 23 30 23M36 1C36 1 41 6 41 15C41 24 36 29 36 29" stroke="black" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
          </div>
        </div>
      </main>
    </>
  )
}
