import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import * as d3 from "d3";
import {useEffect} from "react";
import { useState } from "react";
import { useRef } from "react";

import Mapper from '../components/Mapper'


export default function Test() {

    return(
        <>
        <Head>
        <title>Testing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.test}> Hello
        
        <Mapper /></div>
        </>
    )
}